### ISSUE TITLE
ADO templates YAML

### ISSUE THREAD

**Issue by solomem** [solomem/DevOps#2]
# [Docker Installer task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/docker-installer?view=azure-devops)

```
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
```

# [(build) Docker ](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/containers/build-image?view=azure-devops)

```
trigger:
 - main

 pool:
   vmImage: 'ubuntu-latest' 

 variables:
   imageName: 'pipelines-javascript-docker'

 steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: $(imageName)
     command: build
     Dockerfile: app/Dockerfile
```
